Capstone project for HVAC summit
MarkoKermi/Capstone-project---Conference-page pull request #1
Opened 2023-01-04 22:18 UTC by MarkoKermi

- index.html creation of the main page. 
- style.css creation of decoration file for the main index page. 
- about.html creation of about file, second html file linked with the main page via dropdown menu button. 
- creation of JS file for "Future speakers" part of the main page and for burger menu. 
- creation of Readme file

2023-01-04 22:41 UTC, MarkoKermi commented
Bellow you can find the link from the video where i present my Capstone project: 

https://www.loom.com/share/7154e6e3e51f415ba05bf8be27f6767a

2023-01-05 00:38 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @MarkoKermi , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅  Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 00:38 UTC, joskalenda commented on index.html
> +            <a href="#news" class="nav-item">News</a>
- [ ] I really liked your topic, `technical drawing`, this was so a good choice by the way, but there are a few changes I will raise before the work got approved, except the content of the page which can change according to your chosen topic, everything (style and layout) else needs to be the same as in the original design, this is what you did not really follow in this project, see this below

<img width="1257" alt="1" src="https://user-images.githubusercontent.com/77843050/210669852-652eddf6-51bb-431c-8d88-eeee6bd252ce.png">


- [ ]  Starting from the header, there is a missing section before it that contains social media icons and other stuff, it is required that is why I would ask you to add it, please.

- [ ] The `about text is in red color in the original design and the last item is in red too and has a red border, please make sure you update yours to look like so.

- [ ] Kindly use the same design properties as per the original design (font weight, font size, colors, padding, margin, etc...) this hero text is highlighted because it does not match the original design, please compare and make the update) we need a conformed copy of the given template, remember that

- [ ]  The paragraph design is missing some adjustments to match the original design, it is large, and the box background has not had the correct color, please fix this too.

2023-01-05 00:38 UTC, joskalenda commented on index.html
> +
- [ ] Please make a few touches to update your design to look like the original design on the left of the image below

<img width="1230" alt="2" src="https://user-images.githubusercontent.com/77843050/210671039-027f0a94-01a0-4e99-93aa-da30f2282d0b.png">

- [ ]  The `main program` text is not sharing the same font weight and spaces as the original design does, please update that

- [ ]  There is a half line under the `main program` text, kindly add it too

- [ ]  your program alignment is not what is required, please follow my red boxes as they represent the design of the original template and make the update and consider adding one more program to make them `5`

- [ ]  The last text is not supposed to be a button, just a simple line of text instead, please fix it and adjust the alignments of the entire app @MarkoKermi

2023-01-05 00:38 UTC, joskalenda commented on index.html
> +  <section class="featured_speakers" id="resume"></section>
- [ ] Well done on creating this section dynamically, but there are still a few steps to work on in the styling to get the project on the stage to be approved

<img width="1271" alt="3" src="https://user-images.githubusercontent.com/77843050/210671910-a8018bb7-c785-4747-affe-779864aa8fa3.png">

- [ ] As shown with the red box, please make sure you update to match the exact design, the big box on the right is referring to this requirement image below, you need to have 6 speakers, 3 on the left and 3 others on the right, which is not what you have done.

<img width="870" alt="2" src="https://user-images.githubusercontent.com/77843050/210672733-8fe40bcb-b511-4138-aa27-c896dd9d62e3.png">

- [ ] Consider using the same colors, padding, font size, and all as per the correct design

2023-01-05 00:38 UTC, joskalenda commented on index.html
> +      <a target="_blank" href="http://www.pakson.mk/" alt="pakson main page"><img class="icon-logo"
- [ ] Not much to say here, but if I believe my eyes, am sure this background color is not the correct one used in the original design, please change it.
- [ ] The title is not using the same color, padding, and font-weight as the original template, please fix that too

- [ ] And the footer, please follow the red boxes, the image should be aligned on the left abt the other text on the right as you can see from the original design, please update that and resubmit your work


<img width="1269" alt="4" src="https://user-images.githubusercontent.com/77843050/210673135-a41f084f-5aff-4f96-a722-c3be5cfae093.png">

2023-01-05 00:38 UTC, joskalenda commented on script.js
> +
- Nicely done ❤️

2023-01-05 00:38 UTC, joskalenda commented on about.html
> +        projects. HVAC world Skopje Forum will host Mechanical engineers with
- [ ] Everything bordered in red has to be compared with the original design on the left of the image, kindly make sure you arrange your text font weight, color, padding, and background color all as shown in this image below

<img width="1207" alt="6" src="https://user-images.githubusercontent.com/77843050/210673641-7bbc2ac7-3f98-47f3-947b-ec81a9e5640b.png">

- [ ] The text on the images must be entered and make sure you add that red color over the image to match the originally given template

<img width="1187" alt="7" src="https://user-images.githubusercontent.com/77843050/210674022-ee75f543-6aad-4f6b-965e-f6b02d6805da.png">

2023-01-05 00:38 UTC, joskalenda commented on index.html
> +            <a href="#news" class="nav-item">News</a>
- [ ] Please add an (X) close button to the nav bar as per this requirement

<img width="561" alt="1" src="https://user-images.githubusercontent.com/77843050/210675276-7dc7719f-2a25-42d4-87f9-ea80e3f1b3a0.png">


- [ ] I think it was intentional to leave that white space on the top and left side of the nav menu but I would suggest you remove it, it is always fine to cover an entire section or if you need to make it half, then make it half but do not leave a few spaces as you did, I don't think it is a good idea

<img width="370" alt="9" src="https://user-images.githubusercontent.com/77843050/210675206-afb018bd-461d-4b47-ac1b-301fb3c146aa.png">

2023-01-06 12:36 UTC, algerina requested changes
Hi @MarkoKermi,
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## REQUIRED CHANGES 
kindly check the comments under the review.

<img src="https://media0.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

 
 ## Optional suggestions
 
 - Please check the comment under the review.

## You can also consider:
- Getting rid of the Logo and title on the Readme and changing it to your project title.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-01-06 12:36 UTC, algerina commented on index.html
> +  <section class="featured_speakers" id="resume"></section>
- [ ] In the footer the logo should be aligned to the left and the text should be aligned to the right as required by the previous reviewer to match the design, kindly fix the alignment.

2023-01-06 12:36 UTC, algerina commented on style.css
> +}
- [ Optional]  I will recommend you maximize the font weight and make the title in 2 lines to match the design.

2023-01-06 13:54 UTC, omarsalem7 approved these changes
Hi @MarkoKermi 😊, 

# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/10xZU9b7JBx14s/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper description ✔️
- The project has met all the technical aspects you needed for this project. Keep rocking!  ✔️


Cheers and Happy coding!👏👏👏

## Optional suggestions

- [ ] [OPTIOAL] Kindly fix the broken MIT link and add your own license.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 16:21 UTC, merged